Add new storage class and fix rbac
flant/yandex-csi-driver pull request #9
Opened 2021-11-25 12:07 UTC by vortland

2021-11-25 12:16 UTC, zuzzas requested changes

2021-11-25 12:16 UTC, zuzzas commented on deploy/1.17/rbac.yaml
> +    verbs: ["list", "watch"]
```suggestion
    verbs: ["get", "list", "watch"]
```

2021-11-26 06:48 UTC, zuzzas commented
Thanks!

2021-11-26 06:48 UTC, zuzzas approved these changes

2021-11-26 06:49 UTC, merged

2021-11-26 06:56 UTC, vortland commented
you're welcome)